# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: macos-latest

steps:

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      
      brew install node
      
      npm install cypress --save-dev
      
      npm install junit-report-merger --save-dev
  displayName: 'cypress install'
  
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'npx cypress run'
  displayName: 'run cypress'
  continueOnError: true

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      npm run merge:reports
  displayName: 'merge reports'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'automation-report.xml'
    searchFolder: '$(System.DefaultWorkingDirectory)'